version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gin_devops
      - MYSQL_USER=fleezesd
      - MYSQL_PASSWORD=1234
      - TZ=Asia/Shanghai
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"